apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: storage
  labels:
    type: local
spec:
  #  storageClassName:
  capacity:
    storage: 100Mi
  nfs:
    path: /var/nfs/general
    server: 192.168.0.229
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-claim
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi





---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-test
  namespace: storage
  labels:
    app: nfs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-test
  template:
    metadata:
      labels:
        app: nfs-test
    spec:
      containers:
        - name: nfs-test
          image: busybox
          command:
            - sleep
            - "3600"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /test1
              name: nfs
      restartPolicy: Always
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-test-claim
            readOnly: false
