apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: example.com/external-nfs
parameters:
  server: 192.168.0.229
  path: /var/nfs/general
  readOnly: "false"

