apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-v2
  namespace: nelly-v1
  labels:
    app: spring-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo2
  template:
    metadata:
      name: spring-demo2
      labels:
        app: spring-demo2
    spec:
      containers:
        - name: spring-demo2-db
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-demo-db-secret
                  key: password
        - name: spring-demo2
          image: nellyssenkumba/demo-spring-app:1.0.0-beta-no-db
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7100
              protocol: TCP
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-demo-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-demo-db-secret
                  key: password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-demo-config
                  key: db_url2
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo2
  namespace: nelly-v1
spec:
  selector:
    app: spring-demo
  ports:
    - protocol: TCP
      name: app
      port: 7101
      targetPort: 7100
    - port: 5433
      name: db
      targetPort: 5432
      protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo2-headless
  namespace: nelly-v1
spec:
  clusterIP: None
  selector:
    app: spring-demo
  ports:
    - protocol: TCP
      name: app
      port: 7101
      targetPort: 7100
    - port: 5433
      name: db
      targetPort: 5432
      protocol: TCP
