apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-demo-config
data:
  #  db_url: "jdbc:postgresql://10.0.10.40:5433/demo"
  db_url: "jdbc:postgresql://spring-demo-db:5433/demo"
#  db_url2: "jdbc:postgresql://localhost:5432/demo"

