apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-postgres
  namespace: nelly-v1
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: spring-demo-db
          image: postgres:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-demo-db-secret
                  key: password
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-db
  namespace: nelly-v1

spec:
  selector:
    app: spring-demo-postgres
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432

