apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-db-data
  namespace: nelly-v1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/c/Users/User/Documents/Eng/Sybyl/postgres_data
