apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-11-05T11:07:52Z"
  generation: 1
  labels:
    app: mongo-depl
  name: mongo-depl
  namespace: my-namespace
  resourceVersion: "15627"
  uid: 1539c53b-777c-40c4-9e1f-70054b44864e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongo-depl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-depl
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Always
        name: mongo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-05T11:21:49Z"
    lastUpdateTime: "2024-11-05T11:21:49Z"
    message: ReplicaSet "mongo-depl-67d7db846c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-11-06T05:48:00Z"
    lastUpdateTime: "2024-11-06T05:48:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
