apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: nelly-v1
  labels:
    app: postgres-db
spec:
  replicas: 9
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      name: postgres-db
      labels:
        app: postgres-db
    spec:
      containers:
        - name: spring-demo-db
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: demo
      restartPolicy: Always
  serviceName: postgres-svc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: nelly-v1
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
