apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness
  namespace: probes
  labels:
    app: readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      name: readiness
      labels:
        app: readiness
    spec:
      containers:
        - name: readiness
          image: registry.k8s.io/goproxy:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10


      
