apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: certified
  namespace: nelly-v1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - nelly.com
      secretName: nelly-certificate
  ingressClassName: nginx
  rules:
    - host: nelly.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: spring-demo
                port:
                  number: 7100

