apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb
spec:
  addresses:
    - 192.168.0.29/32
    - 192.168.0.239/32
    - 192.168.0.247/32
    - 192.168.0.126/32


---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ip-advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - ip-pool
